pipeline:
  name: telecom-monitoring-pipeline
  identifier: telecommonitoringpipeline
  projectIdentifier: CI_pipeline
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.githubconnector
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-22
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build and Test
                  identifier: Maven_Build_and_Test
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get update
                      sudo apt-get install -y openjdk-17-jdk

                      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                      export PATH=$JAVA_HOME/bin:$PATH

                      java -version
                      mvn -version

                      chmod +x mvnw
                      ./mvnw clean test
