pipeline:
  name: telecom-monitoring-pipeline
  identifier: telecommonitoringpipeline
  projectIdentifier: CI_pipeline
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.githubconnector
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-22
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build and Test
                  identifier: Maven_Build_and_Test
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get update
                      sudo apt-get install -y openjdk-17-jdk

                      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                      export PATH=$JAVA_HOME/bin:$PATH

                      java -version
                      mvn -version

                      chmod +x mvnw
                      ./mvnw clean test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhubconnector
                    repo: yadavkk/telecom-monitoring-app
                    tags:
                      - latest
                    caching: true
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: telecommonitoringservice
          environment:
            environmentRef: dockerdesktopdev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dockerdesktopinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
